build: $(shell cargo build --release)
	$(info )
	$(info Add the following line to ~/.bash_profile to enable:)
	$(info )
	$(info $(SPACE) PROMPT_COMMAND='PS1=$$($(shell pwd)/target/release/git_term)';)
	$(info )